services:
  - type: web
    name: escape-room
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
